apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
